# Generated by Django 3.1.3 on 2020-11-10 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_checkout'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='checkout',
            unique_together={('user', 'product')},
        ),
    ]
